services:
  postgres:
    image: postgres:15
    container_name: remindz_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: remindz
      POSTGRES_PASSWORD: remindz
      POSTGRES_DB: remindz
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: remindz_redis
    ports:
      - "6379:6379"


  duckling:
    image: rasa/duckling:latest
    container_name: memvix_duckling
    platform: linux/amd64
    ports:
      - "8001:8000"
    restart: unless-stopped



volumes:
  pgdata:
